### ISSUE TITLE
providing the pickle files available and the rest of the data

### ISSUE THREAD

**Issue by brando90** [WangYueFt/rfs#9]
Hi,

can you provide code to be able to get the data from this repo? It's not exactly reproducible in it's current format.

**Comment by brando90** [comment]
@WangYueFt @HobbitLong 
I am getting this error:

```
Traceback (most recent call last):
  File "/Users/brando/anaconda3/envs/automl-meta-learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-323a167d4f3c>", line 190, in <module>
    metaimagenet = MetaImageNet(args)
  File "<ipython-input-6-323a167d4f3c>", line 98, in __init__
    super(MetaImageNet, self).__init__(args, partition, False)
  File "<ipython-input-6-323a167d4f3c>", line 48, in __init__
    with open(os.path.join(self.data_root, self.file_pattern % partition), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/brando/data/miniImageNet_rfs/miniImageNet_category_split_train.pickle'
```

is there something missing the the drive files you've provided?
